### ISSUE TITLE
Merge Adjacent Cylinders

### ISSUE THREAD

**Issue by saraedum** [flatsurf/flatsurf#116]
Vertical connections can sometimes break up cylinders (or non-keane non-periodic components) in trivial ways.

When that happens we should merge them back together before reporting them in FlowDecomposition.

**Comment by videlec** [comment]
No you should not! When it happens, it means that you have a saddle connection from a marked point to itself. It is useful to know where this point is located and hence to split the cylinder into two.

**Comment by saraedum** [comment]
Great. Let's close this issue then!
