### ISSUE TITLE
Cylinder Deformation

### ISSUE THREAD

**Issue by saraedum** [flatsurf/flatsurf#118]
See mostly Theorem 1.1 of "Cylinder Deformations In Orbit Closures Of Translation Surfaces".

Operations needed for this:

* Flow Decomposition into Cylinders and components without periodic trajectories.
* Geometry of Cylinders (Height & Width)
* Express Cylinder Boundaries as sums of Half Edges of the original Surface
* ?

Test with Veech Surfaces, there the answers are known.

**Comment by videlec** [comment]
We also need an object for _(linear) deformation of surfaces_. That is made of:
- a translation surface S0 defined over a number field K
- a linear space L of deformation defined over K (and that contains S0). The space L is contained in the real cohomology of the surface. The real cohomology, is the subspace of `K^edges` where the sums over each triangle is zero. For example the components of the vectors defining the translation structure `S0` are cohomology classes.
The surface `S0` will not necessarily be the one to be used for cylinder deformations and only serves as a base point.

**Comment by videlec** [comment]
More tests (ie known GL(2,R)-orbit closures):
- Veech surfaces (dimension 4): 2n-gons, double n-gons, Bouw-Moeller surfaces, quadratic Veech surfaces in arithmetic rank 2 (McMullen)
- loci coming from orientation cover of quadratic differentials (`surface_dynamics` can produce that easily)
- ramified cover of already known loci
   - over periodic point (same dimension, includes square-tiled surfaces)
   - over non-periodic point (get 2 more dimensions)
   -  maybe have a look at https://arxiv.org/abs/1708.03411
- exotic examples of McMullen-Mukamel-Wright (https://annals.math.princeton.edu/mcmullen-mukamel-wright)

**Comment by videlec** [comment]
This is now: https://github.com/flatsurf/sage-flatsurf/issues/34
