### ISSUE TITLE
more functionalities for Python FlowDecomposition object

### ISSUE THREAD

**Issue by videlec** [flatsurf/flatsurf#204]
In order to avoid an extra wrapper we plug methods onto the cppyy objects as needed for https://github.com/flatsurf/sage-flatsurf/pull/51

- `def cylinders(self):` Return the cylinders (aka completely periodic components)
- `def minimalComponents(self):`: Return the minimal components
- `def undeterminedComponents(self):` Return the undetermined components that could either be cylinder or minimal components.
- ~~`def num_cylinders_minimals_undetermined(self):` Return the triple of numbers of respectively cylinders, minimal components and undetermined components~~ this can easily be implemented from the abvoe ones via `len(xxx)`

**Comment by videlec** [comment]
@saraedum Do you agree on method names? Last chance to change...

**Comment by saraedum** [comment]
I think we should stick to the camelCase that we already have from the C++ side.

**Comment by saraedum** [comment]
Is `num_cylinders_minimals_undetermined` really helpful? It's trivial to say `len(cylinders())` and so on instead so I think this mostly clutters the interface. Note that creating a component is very cheap so there should not be a performance argument here.

**Comment by videlec** [comment]
Sure.
