### ISSUE TITLE
expose the SAF invariant of FlowDecomposition

### ISSUE THREAD

**Issue by videlec** [flatsurf/flatsurf#297]
The SAF invariant is very relevant when we have minimal components. We actually do compute it via the `libintervalxt` to check for Boshernitzan criterion (the SAF is an invariant of the vertical foliation and can be computed on _any_ interval exchange). This does not seem to be nicely exposed through the Python interface.

**Comment by saraedum** [comment]
I guess you want the SAF invariant of a flow component instead of the one of the entire flow decomposition. Anyway, that should be really easy to expose.

**Comment by saraedum** [comment]
So, here's something that should but does not work:
```py
sage: import cppyy
sage: cppyy.include('intervalxt/component.hpp') # :( missing include when cppyy sees an intervalxt object.
True
sage: from flatsurf import translation_surfaces
sage: from flatsurf import GL2ROrbitClosure
sage: S = translation_surfaces.mcmullen_L(1, 1, 1, 1)
sage: O = GL2ROrbitClosure(S)
sage: D = next(O.decompositions(bound=8))
sage: C = D.components()[0R]
sage: C
Cylinder with perimeter [6 → 4 → 7 → 1 → -6 → -4 → -7 → -1]
sage: C = C.dynamicalComponent()
sage: C.iet()
segfault
```
