### ISSUE TITLE
Python string representation is missing a ')' at the end

### ISSUE THREAD

**Issue by videlec** [flatsurf/flatsurf#311]
```
>>> import gmpxxyy
>>> from pyflatsurf.vector import Vectors
>>> from pyflatsurf.factory import make_surface
>>> V2 = Vectors(gmpxxyy.mpq)
>>> vertices = [(1, -3, 2, -1, 6, -5), (-2, 4, -6, 5, -4, 3)]
>>> vectors = [V2((1, 1)), V2((-1, 0)), V2((0, -1)), V2((1, 1)), V2((-1, 0)), V2((0, -1))]
>>> make_surface(vertices, [v.vector for v in vectors])
FlatTriangulationCombinatorial(vertices = (1, -3, 2, -1, 6, -5)(-2, 4, -6, 5, -4, 3), faces = (1, 2, 3)(-1, -5, -6)(-2, -3, -4)(4, 5, 6)) with vectors {1: (1, 1), 2: (-1, 0), 3: (0, -1), 4: (1, 1), 5: (-1, 0), 6: (0, -1)}
```
The string in the last line above is missing a `)` at the very end.

**Comment by saraedum** [comment]
I think the string is fine:

```py
repr = 'FlatTriangulationCombinatorial(vertices = (1, -3, 2, -1, 6, -5)(-2, 4, -6, 5, -4, 3), faces = (1, 2, 3)(-1, -5, -6)(-2, -3, -4)(4, 5, 6)) with vectors {1: (1, 1), 2: (-1, 0), 3: (0, -1), 4: (1, 1), 5: (-1, 0), 6: (0, -1)}'
>>> repr.count('(')
13
>>> repr.count(')')
13
```

What's probably confusing you is that it says `FlatTriangulationCombinatorials(…) with vectors {…}`. So it's a combinatorial triangulation with additional vectors which makes it a flat triangulation.

**Comment by saraedum** [comment]
We should probably change that if it's confusing so it says `FlatTriangulation(vertices=…, faces=…, vectors=…)`.

**Comment by videlec** [comment]
Indeed, I was just confused.

I tend to prefer representation that you can copy paste to get your object back.

**Comment by saraedum** [comment]
> I tend to prefer representation that you can copy paste to get your object back.

Me too. I decided against it here because (except for such a trivial case) this is essentially hopeless. If the vectors are not just rational numbers, how would encode their parent ring?
