### ISSUE TITLE
Interface with flatsurf, surface_dynamics, veerer and flipper

### ISSUE THREAD

**Issue by videlec** [flatsurf/flatsurf#47]
Several Python libraries deals with similar things and it should be possible to talk to them.  For example
- [flatsurf](https://github.com/videlec/sage-flatsurf): see #75
- [surface_dynamics](https://gitlab.com/videlec/surface_dynamics)
- [veerer](https://gitlab.com/videlec/veerer/)
- [flipper](https://bitbucket.org/Mark_Bell/flipper)

Here is a sample file that contains examples on how to build "flat polygonization data" from some of them:
[use_cases.py.txt](https://github.com/polygon-tbd/polygon/files/2845480/use_cases.py.txt).

**Comment by videlec** [comment]
Should the converters `pyeantic number field` <-> `SageMath number field` be directly in pyeantic?

**Comment by saraedum** [comment]
Yes, that seems very reasonable to me.

**Comment by videlec** [comment]
See https://github.com/flatsurf/pyeantic/pull/12

**Comment by videlec** [comment]
We agreed that pyflatsurf should be (as much as possible) Sage agnostic and that any high level conversion would go through sage-flatsurf.
