### ISSUE TITLE
configure does not find exact-real

### ISSUE THREAD

**Issue by videlec** [flatsurf/flatsurf#95]
Even though I (hope I) did install exact-real, configure fails
```
checking for exactreal::RealNumber::random() in -lexactreal... no
configure: error: exact-real library not found
```
[config.log](https://github.com/flatsurf/flatsurf/files/3490318/config.log)

**Comment by saraedum** [comment]
Sorry, that's a known bug. I am fixing it in #94

**Comment by saraedum** [comment]
Should be fixed now. Please reopen if it isn't.
