### ISSUE TITLE
configure failure (because of exact-real)

### ISSUE THREAD

**Issue by videlec** [flatsurf/flatsurf#97]
#95 was fixed but I am still not able to compile
```
checking exact-real/real_number.hpp usability... no
checking exact-real/real_number.hpp presence... yes
configure: WARNING: exact-real/real_number.hpp: present but cannot be compiled
configure: WARNING: exact-real/real_number.hpp:     check for missing prerequisite headers?
configure: WARNING: exact-real/real_number.hpp: see the Autoconf documentation
configure: WARNING: exact-real/real_number.hpp:     section "Present But Cannot Be Compiled"
configure: WARNING: exact-real/real_number.hpp: proceeding with the compiler's result
configure: WARNING:     ## ------------------------------------ ##
configure: WARNING:     ## Report this to julian.rueth@fsfe.org ##
configure: WARNING:     ## ------------------------------------ ##
checking for exact-real/real_number.hpp... no
configure: error: libexactreal headers not found
configure: error: ./configure failed for 
flatsurf-polygon
```
[config.log](https://github.com/flatsurf/flatsurf/files/3494448/config.log)

**Comment by saraedum** [comment]
Could you attach the `config.log` of `libflatsurf`, i.e., the one in `libflatsurf/`?

**Comment by videlec** [comment]
[libflatsurf-config.log](https://github.com/flatsurf/flatsurf/files/3497062/libflatsurf-config.log)

**Comment by saraedum** [comment]
Sorry, I had edited the above. I don't need the libflatsurf one but the flasturf-polygon.

**Comment by saraedum** [comment]
So, in libflatsurf, everything is fine:
```
configure:14063: checking for exact-real/real_number.hpp
configure:14063: result: yes
```

**Comment by videlec** [comment]
- [pyflatsurf-config.log](https://github.com/flatsurf/flatsurf/files/3497090/pyflatsurf-config.log)
- [flatsurf-polygon-config.log](https://github.com/flatsurf/flatsurf/files/3497091/flatsurf-polygon-config.log)

**Comment by saraedum** [comment]
Fixed. Please try again. (You need to run `./bootstrap` I think.)

**Comment by saraedum** [comment]
Feel free to reopen if the problem persists.
