### ISSUE TITLE
test-suite failure

### ISSUE THREAD

**Issue by videlec** [flatsurf/flatsurf#98]
(now configuration/compilation passes... youhou). But
```
============================================================================
Testsuite summary for pyflatsurf 0.0.1
============================================================================
# TOTAL: 4
# PASS:  3
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See test/test-suite.log
Please report to julian.rueth@fsfe.org
============================================================================
```
[pyflatsurf-test-suite.log](https://github.com/flatsurf/flatsurf/files/3498241/pyflatsurf-test-suite.log)

**Comment by saraedum** [comment]
Some ideas:
* Do you have `libflatsurf.so` installed somehow? Try `make uninstall`.
* Do you have the latest cppyy? (from pip I guess?)

The actual error is this one. This 
```
IncrementalExecutor::executeFunction: symbol '_ZN8flatsurf6VectorIN9exactreal7ElementINS1_11NumberFieldEEEEC1ERKS4_S7_' unresolved while linking symbol '__cf_76'!
You are probably missing the definition of flatsurf::Vector<exactreal::Element<exactreal::NumberField> >::Vector(exactreal::Element<exactreal::NumberField> const&, exactreal::Element<exactreal::NumberField> const&)
Maybe you need to load the corresponding shared library?
```

Can you check whether your `libflatsurf.so` contains the symbol `_ZN8flatsurf6VectorIN9exactreal7ElementINS1_11NumberFieldEEEEC1ERKS4_S7_`? You can check with `objdump -T`.

**Comment by videlec** [comment]
>     * Do you have `libflatsurf.so` installed somehow? Try `make uninstall`.

That was it!  Why isn't the local one prefered?

**Comment by saraedum** [comment]
Good question. Let me check.

**Comment by saraedum** [comment]
I fear that's how cling works. You can only add more paths to the library search path. But you cannot specify that that path should always be prioritized.
